declare type Ithis = {
  addIndicator: Function,
  addListener: Function,
  addTalibIndicator: Function,
  addTulipIndicator: Function,
  advice: Function,
  calculateSyncIndicators: Function,
  check: Function,
  emit: Function,
  eventNames: Function,
  finish: Function,
  getMaxListeners: Function,
  init: Function,
  isBusy: Function,
  listenerCount: Function,
  listeners: Function,
  notify: Function,
  off: Function,
  on: Function,
  once: Function,
  prependListener: Function,
  prependOnceListener: Function,
  processTrade: Function,
  propogateTick: Function,
  rawListeners: Function,
  removeAllListeners: Function,
  removeListener: Function,
  setMaxListeners: Function,
  tick: Function,
  update: Function,
  age: 90,
  processedTicks: 90,
  setup: true,
  settings: {
    short: 20,
    long: 10,
    signal: 9,
    thresholds: { down: -0.025, up: 0.025, persistence: 1 },
  },
  tradingAdvisor: {
    enabled: true,
    method: 'MyMACD',
    candleSize: 1440,
    historySize: 10,
  },
  priceValue: 'close',
  indicators: {
    macd: {
      Indicator: {
        input: 'price',
        diff: 0.002664258444506906,
        short: {
          Indicator: {
            input: 'price',
            weight: 20,
            result: 2.4858304551483785,
            age: 90,
          },
        },
        long: {
          Indicator: {
            input: 'price',
            weight: 10,
            result: 2.4831661967038716,
            age: 90,
          },
        },
        signal: {
          Indicator: {
            input: 'price',
            weight: 9,
            result: 0.1765519127184871,
            age: 90,
          },
        },
        result: -0.1738876542739802,
      },
    },
    asyncTick: false,
    deferredTicks: [],
    propogatedAdvices: 4,
    completedWarmup: true,
    end: Function,
    onTrade: Function,
    trend: { duration: 11, persisted: true, direction: 'down', adviced: true },
    requiredHistory: 10,
    log: Function,
    _events: {
      [Object]: {
        stratWarmupCompleted: Function,
        advice: Function,
        stratUpdate: Function,
        stratNotification: Function,
        tradeCompleted: Function,
      },
    },
    _eventsCount: 5,
    candle: {
      start: '2018-12-23 01:46:00',
      open: 2.6758,
      high: 2.9775,
      low: 2.6666,
      close: 2.9667,
      vwp: 2.822153654743123,
      volume: 14319957.570000004,
      trades: 94869,
    },
    _currentDirection: 'short',
    _pendingTriggerAdvice: null,
  },
};
